### ISSUE TITLE
evaluateModule should either be omitted or throw an error until it can do the right thing

### ISSUE THREAD

**Issue by erights** [Agoric/evaluate#2]
`evaluateModule` currently has the same behavior as `evaluateProgram`. This defeats the purpose of distinguishing different evaluators so we don't mistake one for the other.

For the real SES one, it is not at all clear what `evaluateModule` should even evaluate to. It if is intended to be like the import expression, then it should kick off transitive linking and loading, and return a promise for the module object representing what the top level module will export. If it is intended as the low level hook on which we build loader behavior, then it should return something like a static module record.

Until we figure out what the real one should do, and even whether its evaluator belongs here, we do not have enough info to support here an unsafe emulation. I think this should be omitted until we have figured out what we want from a SES module system.

**Comment by michaelfig** [comment]
Actually `evaluateModule` has different behaviour than `evaluateProgram`.  It is in bed with `default-evaluator-options`, which enables the rewrite from 'module' source to 'program' source before evaluation.

It currently results in something like the `import()` expression, except with anonymous module text.  Indeed it returns a promise for the module namespace object and is hooked into the `import()` expression implementation.

If you are uncomfortable with this we can reevaluate (no pun intended) this behaviour before moving forward.  I was hoping to prototype the intended SES behaviour here, and if we do need to change it in the future we can call it an API change and bump the major number.  I'm not too concerned about breaking compatibility.

**Comment by erights** [comment]
> Actually evaluateModule has different behaviour than evaluateProgram. It is in bed with default-evaluator-options, which enables the rewrite from 'module' source to 'program' source before evaluation.

In that case I am confused. Don't yet change anything based on my confused feedback. Wait until we regroup and you de-confuse me.

**Comment by michaelfig** [comment]
No, actually it was I who was confused.  I was mixing up the work I was doing in transform-module, which is not yet merged with default-evaluator-options.

I will propose a PR that will cause evaluateModule to fail by default, but not if used with a modules-aware transform (like transform-module).  I thought this work was already done, but it wasn't.

Good catch!

**Comment by warner** [comment]
in the old repo. this was evaluate issue 2
